# 1. Choose how GitVersion calculates versions on merges
mode: ContinuousDelivery

# 2. Enable bumping based on Conventional Commits headers/footers
commit-message-incrementing: Enabled

major-version-bump-message: "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\\([\\w\\s-,/\\\\]*\\))?(!:|:.*\\n\\n((.+\\n)+\\n)?BREAKING CHANGE:\\s.+)"
minor-version-bump-message: "^(feat)(\\([\\w\\s-,/\\\\]*\\))?:"
patch-version-bump-message: "^(fix|perf)(\\([\\w\\s-,/\\\\]*\\))?:"

# 3. Define how each branch type influences the SemVer bump and tags
branches:
  main:
    regex: ^main$                     # your production branch
    label: ''                           # no prerelease label
    increment: Patch                  # default bump on merge into main

  develop:
    regex: ^develop$                  # integration branch
    label: 'alpha'                      # prerelease label (e.g. 1.2.3-alpha.1)
    increment: Minor                  # minor bump when features land here

  feature:
    regex: ^feature[/-]               # any branch named feature/...
    label: 'beta'                       # prerelease label for feature work
    increment: Patch                  # patch bump per feature commit
    prevent-increment:
      of-merged-branch: true
      when-branch-merged: false
      when-current-commit-tagged: true

  hotfix:
    regex: ^hotfix[/-]                # urgent fixes off main
    label: ''                           # no prerelease on hotfix
    increment: Patch                  # patch bump on hotfix finish

  release:
    regex: ^release[/-]               # release/x.y.z branches
    label: ''                           # tags on main will carry vX.Y.Z
    increment: None                   # use the branch name as the version

# 4. (Optional) ignore specific commits by SHA
ignore:
  sha: []
