apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-binding-default
  namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins
subjects:
- kind: ServiceAccount
  name: default
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jenkins
  name: jenkins
rules:
  - apiGroups: ["", "apps", "serving.kserve.io"]
    resources: [
      "pods", 
      "pods/log", 
      "services", 
      "endpoints", 
      "persistentvolumeclaims", 
      "configmaps", 
      "secrets", 
      "deployments", 
      "namespaces", 
      "inferenceservices"
    ]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
